### ISSUE TITLE
Make build failing

### ISSUE THREAD

**Issue by Jacarte** [PLSysSec/swivel#3]
Hi there !

I am trying to run `make build`. Yet I am getting the following error when it starts to build `lucet-spectre`:

```
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-o" "/datadrive/swivel/lucet-spectre/target/debug/build/cranelift-spectre-d8cae6efe4495c01/out/c_src/btb_flush.o" "-c" "c_src/btb_flush.c"
cargo:warning=c_src/btb_flush.c:9:11: fatal error: ../../../../hw_isol_gem5/tests/test-progs/hfi/hfi.h: No such file or directory
cargo:warning=    9 |  #include "../../../../hw_isol_gem5/tests/test-progs/hfi/hfi.h”
```

I am following the steps mentioned in the README in an isolated ubuntu 20.04 machine.

Any idea about how can I solve this?

Thanks in advance !

**Comment by shravanrn** [comment]
Oh, looks like some changes from other projects have got mixed in. I'll try to fix this soon and post here

**Comment by shravanrn** [comment]
Just pushed a fix to the main swivel repo's makefile. You can restart the build or alternately you can delete the lucet-spectre directory and replace it with

```
git clone https://github.com/PLSysSec/lucet-spectre.git $@
git checkout -b working b1c24732e4ede7b34a582d6b51e5de167608400c
cd $@ && git submodule update --init --recursive
```

**Comment by Jacarte** [comment]
> Just pushed a fix to the main swivel repo's makefile. You can pull the main repo and re-build from scratch or alternately you can delete the lucet-spectre directory and replace it with
> 
> ```
> git clone https://github.com/PLSysSec/lucet-spectre.git $@
> git checkout -b working b1c24732e4ede7b34a582d6b51e5de167608400c
> cd $@ && git submodule update --init --recursive
> ```

Thanks :)
